// Roster: stats, special moves, supers and flavor text for all 18 launch fighters (+ DLC teasers).
// Special `type`s are interpreted by fighter.js. Damage is out of ~1000 Patient Stability.

export const FIGHTERS = [
  {
    id: 'trauma', name: 'DR. TRAUMA', short: 'TRAUMA', title: 'THE WANDERING ATTENDING', dept: 'EMERGENCY',
    hp: 1000, walkF: 1.7, walkB: 1.3, rival: 'surgeon', color: '#d42a2a',
    bio: 'Has worked 31 consecutive shifts. Believes the answer is always a stronger fist.',
    taunt: 'HAVE YOU TRIED TURNING IT OFF AND ON AGAIN?',
    specials: [
      { id: 'syringe', name: 'SYRINGE SHOT', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'syringe', dmg: 62, speed: [2.6, 3.4, 4.2], startup: 12, recovery: 26, ex: { dmg: 100, hits: 2, speed: 4.6 } },
      { id: 'rib', name: 'RIB SPREADER UPPER', input: 'dp', btn: 'p', modern: 'f', type: 'rising', dmg: [90, 110, 130], rise: [5.2, 6.4, 7.6], vx: 1.2, invuln: 6, startup: 3, recovery: 26, ex: { dmg: 160, hits: 3, invuln: 14 } },
      { id: 'cart', name: 'CRASH CART KICK', input: 'qcb', btn: 'k', modern: 'b', type: 'spin', dmg: 42, hits: [1, 2, 3], speed: 2.6, startup: 10, recovery: 14, hover: true, ex: { hits: 5, dmg: 40 } },
    ],
    super: { name: 'CODE BLUE', type: 'beam', color: '#58c8ff', fx: 'zap', line: 'CLEAR!' },
    quotes: ['YOUR VITALS ARE STABLE. YOUR PRIDE IS NOT.', 'I DIDN\'T GO TO MED SCHOOL FOR 12 YEARS TO LOSE TO YOU.', 'NEXT PATIENT! ...PLEASE BE A REAL PATIENT.'],
    story: 'Dr. Trauma has not seen sunlight since residency. Rumors say the Chief of Staff is cutting the ER budget again. He will fight his way up to the boardroom, one consult at a time.',
    choice: ['TAKE THE PROMOTION', 'GO BACK TO THE ER'],
    endings: [
      'Dr. Trauma becomes Associate Vice Chief of Clinical Synergy. He now attends 14 meetings a day and has forgotten how to make a fist. He is very, very sad.',
      'Dr. Trauma returns to the ER. The waiting room cheers. Then 40 ambulances arrive at once. He smiles. This is where he belongs.',
    ],
  },
  {
    id: 'nightingale', name: 'NURSE NIGHTINGALE', short: 'NIGHTINGALE', title: 'THE STRONGEST NURSE IN THE WORLD', dept: 'NURSING',
    hp: 930, walkF: 1.9, walkB: 1.55, rival: 'admin', color: '#f07aac', jump: 1.06,
    bio: 'Twelve-hour shifts, thirteen-hour legs. Has kicked through four staffing shortages.',
    taunt: '*SIGHS AT PAGER* ...THE THIRD TIME THIS MINUTE.',
    specials: [
      { id: 'pill', name: 'PILL POPPER', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'pill', dmg: 50, speed: [3.4, 4.2, 5.0], life: 46, startup: 9, recovery: 22, ex: { dmg: 40, spread: 3 } },
      { id: 'chart', name: 'LIGHTNING CHARTING', input: 'qcb', btn: 'k', modern: 'b', type: 'spin', dmg: 22, hits: [4, 5, 6], speed: 0.4, startup: 8, recovery: 16, poses: ['lkA', 'mkA'], ex: { hits: 9, dmg: 20 } },
      { id: 'turnover', name: 'TURNOVER KICK', input: 'dp', btn: 'k', modern: 'f', type: 'rising', pose: 'hkA', dmg: [80, 100, 120], rise: [5.6, 6.6, 7.4], vx: 1.6, hits: 2, invuln: 5, startup: 4, recovery: 24, ex: { dmg: 150, hits: 4, invuln: 12 } },
    ],
    super: { name: 'RAPID RESPONSE', type: 'rush', color: '#ff8ac8', line: 'CODE TEAM, GO!' },
    quotes: ['I\'VE PULLED TRIPLES WITH LESS EFFORT.', 'CALL ME WHEN YOU CAN HANDLE A 1:8 RATIO.', 'CHARTED: PATIENT GOT ABSOLUTELY WRECKED.'],
    story: 'Administration wants Nightingale to cover six patients, two floors and the gift shop. She has one question for the Administrator, and it comes with a spinning kick.',
    choice: ['DEMAND SAFE RATIOS', 'BECOME A TRAVEL NURSE'],
    endings: [
      'Nightingale storms the boardroom and wins safe staffing ratios for everyone. Nurses worldwide weep with joy. The policy is "under review" until 2087.',
      'Nightingale signs a 13-week travel contract in Hawaii for triple pay. She sends the Administrator a postcard: "WISH YOU WERE HERE (YOU ARE NOT INVITED)."',
    ],
  },
  {
    id: 'surgeon', name: 'THE SURGEON', short: 'SURGEON', title: 'THE STERILE FIELD MARSHAL', dept: 'SURGERY',
    hp: 1080, walkF: 1.6, walkB: 1.45, rival: 'trauma', color: '#3c8a58',
    bio: 'Has never once said "I don\'t know." Scrubs in for breakfast.',
    taunt: 'GO HOME AND BE A FAMILY MAN... AFTER MY 6 AM CASE.',
    specials: [
      { id: 'sonic', name: 'SUTURE SONIC', input: 'chargeBF', btn: 'p', modern: 'n', type: 'projectile', proj: 'thread', dmg: 72, speed: [2.8, 3.6, 4.6], startup: 9, recovery: 18, ex: { dmg: 110, hits: 2, speed: 5 } },
      { id: 'flash', name: 'SCALPEL FLASH', input: 'chargeDU', btn: 'k', modern: 'f', type: 'rising', pose: 'hkA', dmg: [100, 120, 140], rise: [5.0, 6.2, 7.4], vx: 0.6, invuln: 8, startup: 3, recovery: 28, fx: 'slash', ex: { dmg: 170, hits: 2, invuln: 16 } },
      { id: 'retract', name: 'RETRACTOR REACH', input: 'qcf', btn: 'k', modern: 'b', type: 'stretch', pose: 'stretchKA', dmg: 80, startup: 13, active: 4, recovery: 20, guard: 'low', ex: { dmg: 120 } },
    ],
    super: { name: 'SURGICAL TIME-OUT', type: 'rise', color: '#8ae8a8', line: 'TIME OUT. CONFIRMING SITE.' },
    quotes: ['INCISION. EXCISION. DECISION.', 'YOU NEED A SECOND OPINION. IT\'S ALSO MINE.', 'CLOSE HIM UP. ACTUALLY, LEAVE HIM OPEN AS A LESSON.'],
    story: 'The OR schedule has been overbooked by a mysterious force from Admin. The Surgeon will restore order, sterilely.',
    choice: ['OPERATE ON THE CHIEF', 'TAKE A VACATION'],
    endings: [
      'The Surgeon removes the Chief of Staff\'s ego in a 9-hour procedure. It weighs 40 pounds. It is displayed in the hospital museum.',
      'The Surgeon takes his first vacation in 22 years. He spends it reorganizing the resort kitchen\'s knives by sharpness.',
    ],
  },
  {
    id: 'anesth', name: 'ANESTHESIOLOGIST', short: 'ANESTHESIA', title: 'THE SANDMAN OF STRETCH', dept: 'ANESTHESIA',
    hp: 950, walkF: 1.25, walkB: 1.2, rival: 'psych', color: '#2a9aa0',
    bio: 'Sits behind a curtain doing sudoku for 6 hours, then saves your life in 4 seconds.',
    taunt: 'COUNT BACKWARDS FROM TEN FOR ME... 10... 9...',
    specials: [
      { id: 'gas', name: 'SLEEPY GAS', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'gas', dmg: 30, hits: 3, speed: [1.2, 1.6, 2.0], life: 130, startup: 14, recovery: 24, effect: 'slow', w: 22, h: 22, ex: { dmg: 30, hits: 5, speed: 2.2 } },
      { id: 'iv', name: 'IV STRETCH', input: 'qcb', btn: 'p', modern: 'b', type: 'stretch', pose: 'stretchA', dmg: 75, startup: 11, active: 5, recovery: 22, ex: { dmg: 120 } },
      { id: 'milk', name: 'MILK OF AMNESIA', input: 'dp', btn: 'p', modern: 'f', type: 'burst', pose: 'castA', dmg: 95, hits: 2, startup: 6, active: 10, recovery: 26, invuln: 5, fx: 'gas', w: 40, h: 50, ox: 18, oy: 30, ex: { dmg: 140, hits: 3, invuln: 12 } },
    ],
    super: { name: 'COUNT BACKWARDS FROM 10', type: 'zone', color: '#a8f0ff', fx: 'gas', line: '10... 9... 8...' },
    quotes: ['YOU\'LL FEEL A LITTLE PRESSURE. THEN NOTHING. FOREVER.', 'NIGHT NIGHT.', 'I WAS DOING SUDOKU THE WHOLE FIGHT.'],
    story: 'Someone stole the good sudoku books from the OR lounge. The Anesthesiologist will put the entire hospital to sleep until they come back.',
    choice: ['WAKE EVERYONE UP', 'LET THEM SLEEP'],
    endings: [
      'Everyone wakes refreshed. Productivity rises 900%. Admin mistakes it for a new policy and takes credit.',
      'The entire hospital naps for a week. Patient satisfaction scores hit an all-time high. Nobody can explain it.',
    ],
  },
  {
    id: 'pharmacist', name: 'PHARMACIST', short: 'PHARMACY', title: 'KEEPER OF THE FORMULARY', dept: 'PHARMACY',
    hp: 1000, walkF: 1.5, walkB: 1.3, rival: 'admin', color: '#e08020',
    bio: 'Has caught 4,000 drug interactions. Has been thanked twice.',
    taunt: 'THAT WILL BE A $45 CO-PAY. CASH ONLY.',
    specials: [
      { id: 'refill', name: 'REFILL', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'bottle', dmg: 60, lob: true, speed: [2.0, 2.8, 3.6], vy: 4.4, startup: 12, recovery: 22, onLand: 'pills', ex: { dmg: 70, speed: 3.2, onLand: 'pills2' } },
      { id: 'auth', name: 'PRIOR AUTH BEAM', input: 'qcb', btn: 'p', modern: 'b', type: 'beam', dmg: 90, hits: 3, startup: 12, delay: 46, dur: 24, recovery: 16, y: 40, h: 16, color: '#ffd040', label: 'PENDING', ex: { delay: 24, dmg: 130, hits: 4 } },
      { id: 'cap', name: 'CHILDPROOF CAP', input: 'dp', btn: 'p', modern: 'f', type: 'rising', dmg: [85, 105, 125], rise: [5.0, 6.0, 7.0], vx: 1, invuln: 5, startup: 4, recovery: 26, ex: { dmg: 150, hits: 3, invuln: 12 } },
    ],
    super: { name: 'MAX DOSE', type: 'rain', proj: 'pill', color: '#ffa040', line: 'TAKE TWO OF THESE. AND THESE. AND THESE.' },
    quotes: ['DO NOT OPERATE HEAVY MACHINERY. OR FISTS.', 'YOUR PRESCRIPTION FOR DEFEAT IS READY.', 'GENERIC VICTORY. SAME ACTIVE INGREDIENT.'],
    story: 'Insurance denied coverage for the Pharmacist\'s own lunch. Somewhere upstairs, an Administrator laughs. Not for long.',
    choice: ['APPROVE EVERYTHING', 'REQUIRE PRIOR AUTH'],
    endings: [
      'The Pharmacist approves every prescription in the hospital at once. The fax machine achieves sentience and thanks her.',
      'The Pharmacist makes the Administrator fill out a 40-page prior authorization to leave the building. He is still filling it out.',
    ],
  },
  {
    id: 'radiologist', name: 'RADIOLOGIST', short: 'RADIOLOGY', title: 'THE MAN WHO SEES THROUGH YOU', dept: 'RADIOLOGY',
    hp: 1000, walkF: 1.6, walkB: 1.3, rival: 'it', color: '#24346c',
    bio: 'Lives in a dark room. Has not seen a patient\'s face since 2009. Clinical correlation recommended.',
    taunt: 'FINDINGS: NONSPECIFIC. CLINICAL CORRELATION RECOMMENDED.',
    specials: [
      { id: 'xray', name: 'X-RAY READ', input: 'qcf', btn: 'p', modern: 'n', type: 'beam', dmg: 60, hits: 2, startup: 16, delay: 0, dur: 14, recovery: 27, range: [130, 160, 190], y: 44, h: 12, color: '#a8f0ff', effect: 'xray', ex: { dmg: 110, hits: 3, range: [260, 260, 260] } },
      { id: 'contrast', name: 'CONTRAST RUSH', input: 'qcf', btn: 'k', modern: 'f', type: 'rush', dmg: 90, dur: [14, 18, 22], speed: 5.2, startup: 9, recovery: 18, fx: 'glow', ex: { dmg: 130, hits: 2, armor: 1 } },
      { id: 'incidental', name: 'INCIDENTAL FINDING', input: 'dp', btn: 'p', modern: 'b', type: 'rising', dmg: [85, 105, 125], rise: [5.0, 6.0, 7.0], vx: 1.2, invuln: 5, startup: 4, recovery: 26, ex: { dmg: 150, hits: 3, invuln: 12 } },
    ],
    super: { name: 'STAT CT SCAN', type: 'beam', color: '#c8f8ff', effect: 'xray', fx: 'xray', line: 'HOLD YOUR BREATH.' },
    quotes: ['FINDINGS: YOU LOST. IMPRESSION: BADLY.', 'I CAN SEE YOUR BONES. THEY ARE DISAPPOINTED.', 'RECOMMEND FOLLOW-UP BEATDOWN IN 6 MONTHS.'],
    story: 'Someone keeps turning on the lights in the reading room. The Radiologist will find the culprit, and read them like a chest film.',
    choice: ['TURN ON THE LIGHTS', 'STAY IN THE DARK'],
    endings: [
      'The Radiologist steps into sunlight for the first time in a decade. He bursts into flames. Clinical correlation recommended.',
      'The Radiologist remains in the dark forever, reading 9,000 scans a day. He is happy. His dictation software is not.',
    ],
  },
  {
    id: 'ortho', name: 'ORTHO BRO', short: 'ORTHO', title: 'THE RED CYCLONE OF BONES', dept: 'ORTHOPEDICS',
    hp: 1100, walkF: 1.2, walkB: 1.0, rival: 'paramedic', color: '#4060a8', jump: 0.92,
    bio: 'Bench presses patients. Has never read a chart. "Bro, it\'s just carpentry."',
    taunt: 'BRO. DO YOU EVEN LIFT? (THE PATIENT, I MEAN.)',
    specials: [
      { id: 'saw', name: 'BONE SAW', input: 'hcf', btn: 'p', modern: 'n', type: 'grab', dmg: [175, 190, 205], range: [28, 32, 36], startup: 5, recovery: 34, ex: { dmg: 250, range: 44 } },
      { id: 'cast', name: 'CAST CUTTER', input: 'qcf', btn: 'k', modern: 'f', type: 'spin', poses: ['lariat1', 'lariat2'], dmg: 45, hits: [2, 3, 3], speed: 1.0, startup: 6, recovery: 18, invulnUpper: true, ex: { hits: 4, dmg: 45, invuln: 10 } },
      { id: 'protein', name: 'PROTEIN CHARGE', input: 'qcb', btn: 'p', modern: 'b', type: 'rush', dmg: 110, dur: [16, 20, 24], speed: 4.2, startup: 12, recovery: 20, armor: 1, pose: 'dash', ex: { dmg: 150, armor: 2 } },
    ],
    super: { name: 'TOTAL JOINT REPLACEMENT', type: 'grab', color: '#ff6040', line: 'NEW KNEES, BRO!' },
    quotes: ['THAT\'S NOT A FRACTURE, BRO, THAT\'S A FEATURE.', 'I DON\'T DO RECOVERY ROOMS. I DO REPS.', 'HAMMER. CHISEL. SUCCESS. BRO.'],
    story: 'Ortho Bro heard the hospital gym is being converted into more admin offices. Bro. Not on his watch. Not on his leg day.',
    choice: ['OPEN A GYM', 'CHART SOMETHING'],
    endings: [
      'Ortho Bro converts the boardroom into a squat rack. Every executive now has excellent glutes. Morale improves.',
      'Ortho Bro opens the EMR to write a note. He stares at it for 3 hours. He writes "bro." It is the best note in the hospital.',
    ],
  },
  {
    id: 'peds', name: 'PEDIATRICIAN', short: 'PEDS', title: 'THE STICKER SHINOBI', dept: 'PEDIATRICS',
    hp: 920, walkF: 2.0, walkB: 1.6, rival: 'dietitian', color: '#f0d040', jump: 1.08,
    bio: 'Fluent in baby talk, Bluey and seven types of rash. Fears nothing except teenagers.',
    taunt: 'WHO WANTS A STICKER?! NOT YOU. YOU LOST.',
    specials: [
      { id: 'sticker', name: 'STICKER SHURIKEN', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'sticker', dmg: 45, speed: [3.6, 4.4, 5.2], startup: 9, recovery: 20, air: true, ex: { dmg: 40, spread: 3 } },
      { id: 'lolli', name: 'LOLLIPOP LUNGE', input: 'qcf', btn: 'k', modern: 'f', type: 'dive', dmg: 85, vx: [3.2, 3.8, 4.4], vy: 4.6, startup: 8, recovery: 14, guard: 'high', ex: { dmg: 120, hits: 2 } },
      { id: 'hop', name: 'HOPSCOTCH HOP', input: 'qcb', btn: 'k', modern: 'b', type: 'stomp', dmg: 80, vx: [1.6, 2.6, 3.6], vy: 6.4, startup: 6, recovery: 12, guard: 'high', ex: { dmg: 120, hits: 2 } },
    ],
    super: { name: 'SUGAR RUSH', type: 'rush', color: '#ffe040', line: 'WHEEEEEEE!' },
    quotes: ['YOU WERE VERY BRAVE! YOU STILL LOST, BUT VERY BRAVE.', 'NO CRYING IN THE WAITING ROOM.', 'TIME FOR YOUR BOOSTER. OF PAIN.'],
    story: 'The Pediatrician learned that the hospital\'s sticker budget was cut to zero. Small hearts are breaking. Small fists are needed.',
    choice: ['RESTORE THE STICKERS', 'BUY A BOUNCY CASTLE'],
    endings: [
      'Stickers return to the hospital. Children cheer. Adults secretly line up for them too. The Chief of Staff gets a dinosaur one.',
      'The Pediatrician installs a bouncy castle in the ICU. It is a terrible idea. Somehow, every patient improves.',
    ],
  },
  {
    id: 'psych', name: 'PSYCHIATRIST', short: 'PSYCH', title: 'THE MIND PALACE GUARD', dept: 'PSYCHIATRY',
    hp: 1040, walkF: 1.55, walkB: 1.35, rival: 'anesth', color: '#8a6a40',
    bio: 'Has a calm voice, a leather couch and a 50-minute timer. Every fight is a session.',
    taunt: 'AND HOW DOES LOSING MAKE YOU FEEL?',
    specials: [
      { id: 'reframe', name: 'COGNITIVE REFRAME', input: 'qcb', btn: 'p', modern: 'b', type: 'counter', dmg: 130, dur: 32, recovery: 22, ex: { dmg: 170, dur: 40 } },
      { id: 'alliance', name: 'THERAPEUTIC ALLIANCE', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'bubble', dmg: 65, speed: [2.2, 2.8, 3.4], startup: 11, recovery: 20, effect: 'drainMeter', w: 16, h: 14, ex: { dmg: 80, hits: 2, speed: 3.2 } },
      { id: 'ink', name: 'INK BLOT', input: 'dp', btn: 'p', modern: 'f', type: 'burst', pose: 'upA', dmg: 100, hits: 2, startup: 5, active: 9, recovery: 26, invuln: 6, fx: 'ink', w: 34, h: 54, ox: 10, oy: 46, ex: { dmg: 150, hits: 3, invuln: 12 } },
    ],
    super: { name: '50-MINUTE HOUR', type: 'grab', color: '#d0a060', line: 'LIE DOWN. TELL ME ABOUT YOUR MOTHER.' },
    quotes: ['WE\'LL PICK THIS UP NEXT WEEK. SAME TIME.', 'YOUR DEFENSE MECHANISMS ARE... NOT WORKING.', 'I\'M HEARING THAT YOU FEEL DEFEATED.'],
    story: 'The Psychiatrist suspects the entire hospital has a shared delusion that the budget is fine. Group therapy is mandatory. Attendance enforced.',
    choice: ['THERAPY FOR ALL', 'WRITE A BESTSELLER'],
    endings: [
      'The whole hospital attends group therapy. The Administrator finally cries. Everyone hugs. Nothing changes, but it feels better.',
      'The Psychiatrist publishes "Punching Your Feelings: A Clinical Guide." It tops the charts for 70 weeks.',
    ],
  },
  {
    id: 'admin', name: 'ADMINISTRATOR', short: 'ADMIN', title: 'THE DICTATOR OF DENIALS', dept: 'ADMINISTRATION', boss: true,
    hp: 1050, walkF: 1.5, walkB: 1.3, rival: 'nightingale', color: '#d82020',
    bio: 'Has an MBA, a parking spot by the door, and absolute power over your toilet paper budget.',
    taunt: 'PER MY LAST EMAIL...',
    specials: [
      { id: 'denial', name: 'INSURANCE DENIAL', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'stamp', dmg: 60, speed: [2.6, 3.4, 4.2], startup: 12, recovery: 24, effect: 'drainMeter', ex: { dmg: 100, hits: 2, speed: 4.4 } },
      { id: 'cut', name: 'BUDGET CUT', input: 'chargeBF', btn: 'p', modern: 'f', type: 'rush', pose: 'dive', dmg: 30, hits: 4, dur: [18, 22, 26], speed: 5.4, startup: 10, recovery: 20, hover: true, fx: 'money', ex: { dmg: 30, hits: 6, armor: 1 } },
      { id: 'memo', name: 'MEMO STOMP', input: 'chargeDU', btn: 'k', modern: 'b', type: 'stomp', dmg: 90, vx: [2.0, 3.0, 4.0], vy: 7.4, startup: 6, recovery: 14, guard: 'high', ex: { dmg: 130, hits: 2 } },
    ],
    super: { name: 'OUT-OF-NETWORK', type: 'rush', color: '#ff3030', fx: 'money', line: 'YOU ARE NOT COVERED.' },
    quotes: ['YOUR APPEAL HAS BEEN DENIED.', 'I\'VE DECIDED TO RESTRUCTURE YOUR FACE.', 'WE\'RE A FAMILY HERE. YOU\'RE FIRED.'],
    story: 'The Administrator has achieved 107% capacity. To reach 110%, he must eliminate all who oppose the Budget. Synergy will be maximized.',
    choice: ['CUT EVERYTHING', 'GIVE EVERYONE A RAISE'],
    endings: [
      'The Administrator cuts the entire hospital budget, including his own salary, by accident. He now works in the gift shop. Synergy.',
      'In a moment of weakness, the Administrator approves raises for all staff. The universe glitches. He wakes up. It was a dream. Denied.',
    ],
  },
  {
    id: 'janitor', name: 'JANITOR', short: 'JANITOR', title: 'THE BEAST OF THE BASEMENT', dept: 'ENVIRONMENTAL',
    hp: 1000, walkF: 1.8, walkB: 1.4, rival: 'labtech', color: '#5a7a5c',
    bio: 'Has keys to every door. Has seen everything. Has mopped up worse than you.',
    taunt: 'I JUST MOPPED THAT.',
    specials: [
      { id: 'mop', name: 'MOP SLIDE', input: 'qcf', btn: 'k', modern: 'f', type: 'rush', pose: 'slide', dmg: 90, dur: [14, 18, 22], speed: 5.0, startup: 7, recovery: 16, guard: 'low', kd: true, ex: { dmg: 120, hits: 2 } },
      { id: 'wet', name: 'WET FLOOR', input: 'qcb', btn: 'p', modern: 'b', type: 'trap', trap: 'wetfloor', dist: [50, 90, 130], startup: 14, recovery: 18, ex: { dist: [70, 70, 70], count: 2 } },
      { id: 'bio', name: 'BIOHAZARD', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'biobag', dmg: 40, lob: true, speed: [1.8, 2.6, 3.4], vy: 4.8, startup: 14, recovery: 24, onLand: 'cloud', ex: { dmg: 60, onLand: 'cloud2' } },
    ],
    super: { name: 'OSHA VIOLATION', type: 'wave', color: '#60b0ff', line: 'CAUTION! WET FLOOR!' },
    quotes: ['YOU\'RE JUST ANOTHER SPILL IN AISLE FIVE.', 'I\'VE GOT THE KEYS. YOU\'VE GOT NOTHING.', 'WATCH YOUR STEP. TOO LATE.'],
    story: 'Someone tracked mud across the Janitor\'s freshly mopped Grand Rounds Arena. He has one hundred keys and zero patience.',
    choice: ['RETIRE TO FLORIDA', 'BECOME CEO'],
    endings: [
      'The Janitor retires to Florida, where he mops the ocean. Nobody asked him to. It is the cleanest ocean in the world.',
      'The Janitor becomes CEO. The hospital is suddenly spotless, on budget and on time. The board is terrified.',
    ],
  },
  {
    id: 'paramedic', name: 'PARAMEDIC', short: 'MEDIC', title: 'THE LIGHTS & SIRENS BRAWLER', dept: 'EMS',
    hp: 1050, walkF: 1.9, walkB: 1.4, rival: 'ortho', color: '#1c2c5c',
    bio: 'Eats lunch at 70 mph. Has carried a 300-pound man down six flights of stairs. Twice. Same man.',
    taunt: 'I\'VE SEEN WORSE. ON MY WAY HERE.',
    specials: [
      { id: 'siren', name: 'SIREN RUSH', input: 'qcf', btn: 'p', modern: 'n', type: 'rush', dmg: 105, dur: [14, 18, 22], speed: 5.2, startup: 8, recovery: 13, fx: 'siren', ex: { dmg: 140, hits: 2, armor: 1 } },
      { id: 'board', name: 'BACKBOARD BUSTER', input: 'qcf', btn: 'k', modern: 'b', type: 'strike', pose: 'slamA', windup: 'liftA', dmg: 110, startup: 17, active: 4, recovery: 18, guard: 'high', w: 34, h: 34, ox: 18, oy: 20, step: 2, ex: { dmg: 150, kd: true } },
      { id: 'lights', name: 'LIGHTS & SIRENS', input: 'dp', btn: 'p', modern: 'f', type: 'rising', dmg: [95, 115, 135], rise: [5.0, 6.0, 7.2], vx: 1.6, invuln: 5, startup: 3, recovery: 26, ex: { dmg: 160, hits: 3, invuln: 12 } },
    ],
    super: { name: 'GOLDEN HOUR', type: 'rush', color: '#ffd030', fx: 'siren', line: 'LOAD AND GO!' },
    quotes: ['YOU\'RE GOING TO THE ER. I\'M DRIVING.', 'SCOOP AND RUN, BABY!', 'NEXT TIME, CALL A RIDESHARE.'],
    story: 'The ambulance bay was turned into executive parking. The Paramedic is going to park something, and it is his fist.',
    choice: ['GET A NEW AMBULANCE', 'GO TO MED SCHOOL'],
    endings: [
      'The Paramedic gets a brand new ambulance with heated seats and a cappuccino machine. It is stolen by the Administrator within the hour.',
      'The Paramedic goes to medical school. On day one he fixes three things the professor got wrong. They give him the degree early.',
    ],
  },
  {
    id: 'labtech', name: 'LAB TECH', short: 'LAB', title: 'THE CULTURE CURATOR', dept: 'LABORATORY',
    hp: 980, walkF: 1.6, walkB: 1.4, rival: 'janitor', color: '#8060c0',
    bio: 'Spends all day with blood, urine and things growing in dishes. Has never been surprised.',
    taunt: 'SAMPLE HEMOLYZED. REDRAW. AGAIN.',
    specials: [
      { id: 'spill', name: 'SAMPLE SPILL', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'vial', dmg: 35, lob: true, speed: [1.8, 2.6, 3.4], vy: 4.2, startup: 12, recovery: 22, onLand: 'puddle', ex: { dmg: 50, onLand: 'puddle2' } },
      { id: 'centri', name: 'CENTRIFUGE', input: 'qcb', btn: 'k', modern: 'b', type: 'spin', poses: ['spin1', 'spin2'], dmg: 30, hits: [3, 4, 5], speed: 0.2, startup: 7, recovery: 18, invulnUpper: true, ex: { hits: 7, dmg: 28, invuln: 10 } },
      { id: 'pipette', name: 'PIPETTE POKE', input: 'qcf', btn: 'k', modern: 'f', type: 'stretch', pose: 'stretchA', reach: 1.8, dmg: 70, startup: 10, active: 4, recovery: 18, effect: 'poison', ex: { dmg: 110 } },
    ],
    super: { name: 'CULTURE SHOCK', type: 'zone', color: '#b0ff60', fx: 'germ', line: 'IT\'S GROWING...' },
    quotes: ['YOUR RESULTS ARE IN: CRITICAL.', 'I\'VE CULTURED THINGS TOUGHER THAN YOU.', 'PLEASE LABEL YOUR SPECIMENS. AND YOUR LOSSES.'],
    story: 'A mysterious unlabeled specimen appeared in the Lab. It is growing. It is glowing. The Lab Tech will find who sent it.',
    choice: ['DESTROY THE SPECIMEN', 'ADOPT THE SPECIMEN'],
    endings: [
      'The Lab Tech autoclaves the specimen. The hospital is saved. A single tear rolls down her goggles.',
      'The Lab Tech adopts the specimen and names it Gary. Gary now runs Infection Control. Infections are down 100%. Nobody asks how.',
    ],
  },
  {
    id: 'chaplain', name: 'CHAPLAIN', short: 'CHAPLAIN', title: 'THE SERENE COUNTERPUNCHER', dept: 'SPIRITUAL CARE',
    hp: 1050, walkF: 1.4, walkB: 1.3, rival: 'zero', color: '#2e2c3c',
    bio: 'Has calmly sat with 10,000 families. Can end a fight with a single, peaceful uppercut.',
    taunt: 'LET US TAKE A MOMENT... TO REFLECT ON YOUR MISTAKES.',
    specials: [
      { id: 'support', name: 'SPIRITUAL SUPPORT', input: 'qcb', btn: 'p', modern: 'd', type: 'heal', amount: 60, dur: 50, recovery: 10, ex: { amount: 110, armor: 1 } },
      { id: 'silence', name: 'MOMENT OF SILENCE', input: 'qcb', btn: 'k', modern: 'b', type: 'counter', dmg: 120, dur: 30, recovery: 22, freeze: true, ex: { dmg: 170, dur: 40 } },
      { id: 'water', name: 'HOLY WATER', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'water', dmg: 70, speed: [2.8, 3.6, 4.4], startup: 11, recovery: 22, ex: { dmg: 100, hits: 2 } },
    ],
    super: { name: 'LAST RITES', type: 'rain', proj: 'light', color: '#fff0a0', line: 'BE AT PEACE.' },
    quotes: ['GO IN PEACE. AND IN PIECES.', 'I WILL PRAY FOR YOUR RECOVERY. IT WILL TAKE A WHILE.', 'BLESSED ARE THE BLOCKERS.'],
    story: 'Dark energy pulses from Room 0, where Patient Zero lies. The Chaplain must face the outbreak with nothing but faith and frame data.',
    choice: ['FORGIVE PATIENT ZERO', 'START A CHOIR'],
    endings: [
      'The Chaplain forgives Patient Zero. Patient Zero sneezes in gratitude. The Chaplain is out sick for two weeks, but at peace.',
      'The Chaplain starts the hospital choir. Their rendition of "Code Blue Blues" goes triple platinum.',
    ],
  },
  {
    id: 'zero', name: 'PATIENT ZERO', short: 'ZERO', title: 'THE WALKING OUTBREAK', dept: 'ROOM 0', dmgMul: 1.18,
    hp: 820, walkF: 1.8, walkB: 1.5, rival: 'chaplain', color: '#a8c8e8',
    bio: 'Was admitted for "a little cough" in 2019. Has never been discharged. Will not wash hands.',
    taunt: '*COUGH* ...*COUGH COUGH* ...SORRY. *COUGH*',
    specials: [
      { id: 'outbreak', name: 'OUTBREAK', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'sneeze', dmg: 30, hits: 2, speed: [2.0, 2.6, 3.2], life: 70, startup: 10, recovery: 20, effect: 'poison', w: 24, h: 18, ex: { dmg: 30, hits: 4 } },
      { id: 'contagion', name: 'CONTAGION', input: 'qcf', btn: 'k', modern: 'f', type: 'dive', dmg: 80, vx: [3.4, 4.0, 4.6], vy: 3.6, startup: 8, recovery: 14, effect: 'poison', ex: { dmg: 110, hits: 2 } },
      { id: 'pole', name: 'IV POLE VAULT', input: 'dp', btn: 'k', modern: 'b', type: 'rising', pose: 'jhkA', dmg: [90, 110, 130], rise: [5.4, 6.4, 7.4], vx: 2.0, invuln: 5, startup: 4, recovery: 24, ex: { dmg: 150, hits: 3, invuln: 12 } },
    ],
    super: { name: 'PANDEMIC PROTOCOL', type: 'rain', proj: 'germ', color: '#a0ff70', line: 'ACHOOOOOO!' },
    quotes: ['*SNIFF* GOOD GAME. LET\'S SHAKE ON IT.', 'I\'M NOT CONTAGIOUS. MOSTLY.', 'SIX FEET APART WASN\'T ENOUGH, WAS IT?'],
    story: 'Patient Zero overheard the doctors say "discharge." Terrified of the outside world, he will defeat everyone who tries to send him home.',
    choice: ['GO HOME', 'STAY FOREVER'],
    endings: [
      'Patient Zero is finally discharged. He steps outside, sneezes once, and the entire city takes a sick day. Oops.',
      'Patient Zero becomes a permanent resident. He gets a parking spot, a nameplate and his own wing. He still won\'t wash his hands.',
    ],
  },
  {
    id: 'it', name: 'IT SUPPORT', short: 'IT', title: 'THE TICKET TELEPORTER', dept: 'INFORMATION TECH',
    hp: 980, walkF: 1.6, walkB: 1.4, rival: 'radiologist', color: '#3a3a4c',
    bio: 'Appears only when you stop looking for him. Can fix anything by unplugging it.',
    taunt: 'HAVE YOU TRIED TURNING IT OFF AND ON AGAIN?',
    specials: [
      { id: 'ticket', name: 'TICKET ESCALATION', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'ticket', dmg: 55, speed: [2.6, 3.2, 3.8], startup: 11, recovery: 20, grow: true, ex: { dmg: 90, hits: 2 } },
      { id: 'restart', name: 'HAVE YOU RESTARTED?', input: 'dp', btn: 'any', modern: 'f', type: 'teleport', startup: 9, recovery: 7, ex: { recovery: 3 } },
      { id: 'bsod', name: 'BLUE SCREEN', input: 'qcb', btn: 'p', modern: 'b', type: 'burst', pose: 'beamA', dmg: 105, hits: 2, startup: 6, active: 10, recovery: 22, invuln: 6, fx: 'bsod', w: 56, h: 64, ox: 6, oy: 34, ex: { dmg: 130, hits: 3, invuln: 12 } },
    ],
    super: { name: 'SYSTEM REBOOT', type: 'zone', color: '#4080ff', fx: 'bsod', line: 'INSTALLING UPDATES. DO NOT TURN OFF.' },
    quotes: ['TICKET CLOSED. RESOLUTION: USER ERROR.', 'YOUR PASSWORD HAS EXPIRED. SO HAVE YOU.', 'I\'M GOING TO NEED YOU TO RESTART. YOUR CAREER.'],
    story: 'The hospital EMR crashed during a full moon. The Radiologist blames IT. IT blames the Radiologist. Only a fight will close this ticket.',
    choice: ['FIX THE EMR', 'UNPLUG EVERYTHING'],
    endings: [
      'IT Support fixes the EMR. It is now fast, intuitive and loved by all. This is clearly a fantasy ending.',
      'IT Support unplugs the entire hospital. Doctors use paper charts again. Handwriting becomes a lost art. Chaos. Bliss.',
    ],
  },
  {
    id: 'dietitian', name: 'DIETITIAN', short: 'DIET', title: 'THE PORTION CONTROLLER', dept: 'NUTRITION',
    hp: 1000, walkF: 1.7, walkB: 1.4, rival: 'peds', color: '#78c058',
    bio: 'Counts every carb. Judges every lunch. Has never once enjoyed cake.',
    taunt: 'IS THAT... A SECOND DONUT?',
    specials: [
      { id: 'carb', name: 'CARB COUNT', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'bread', dmg: 55, speed: [2.4, 3.2, 4.0], startup: 12, recovery: 24, effect: 'drainGauge', ex: { dmg: 90, hits: 2 } },
      { id: 'slash', name: 'SUPPLEMENT SLASH', input: 'qcf', btn: 'k', modern: 'f', type: 'rush', pose: 'mkA', dmg: 90, dur: [12, 16, 20], speed: 4.8, startup: 8, recovery: 16, ex: { dmg: 130, hits: 2 } },
      { id: 'portion', name: 'PORTION CONTROL', input: 'hcf', btn: 'p', modern: 'b', type: 'grab', dmg: [135, 150, 165], range: [26, 28, 30], startup: 5, recovery: 30, effect: 'drainMeter', ex: { dmg: 200, range: 40 } },
    ],
    super: { name: 'FOOD PYRAMID', type: 'rain', proj: 'food', color: '#ffd060', line: 'EAT YOUR VEGETABLES!' },
    quotes: ['THAT WAS 400 CALORIES OF PURE DEFEAT.', 'BALANCED DIET. UNBALANCED FIGHT.', 'MODERATION IN ALL THINGS. EXCEPT WINNING.'],
    story: 'The cafeteria announced Friday Fish Day will now be every day. The Dietitian has seen the fish. The fish must be stopped.',
    choice: ['BAN FISH DAY', 'ALLOW ONE CHEAT DAY'],
    endings: [
      'The Dietitian bans Friday Fish Day forever. The cafeteria now serves a single kale leaf. Nobody is happy. She is thrilled.',
      'The Dietitian allows one cheat day. She eats one (1) cookie. She weeps. It is the best day of her life.',
    ],
  },
  {
    id: 'chief', name: 'CHIEF OF STAFF', short: 'CHIEF', title: 'MASTER OF THE MANDATORY', dept: 'EXECUTIVE', boss: true,
    hp: 1020, walkF: 1.6, walkB: 1.4, rival: 'trauma', color: '#6a2a8a',
    bio: 'Has not touched a patient since 1994. Every utterance is an Executive Order.',
    taunt: 'LET\'S TAKE THIS OFFLINE. FOREVER.',
    specials: [
      { id: 'order', name: 'EXECUTIVE ORDER', input: 'qcf', btn: 'p', modern: 'n', type: 'projectile', proj: 'orb', dmg: 65, speed: [2.8, 3.6, 4.4], startup: 11, recovery: 24, air: true, ex: { dmg: 110, hits: 2, speed: 4.6 } },
      { id: 'invite', name: 'MEETING INVITE', input: 'qcb', btn: 'p', modern: 'b', type: 'drop', dmg: 90, delay: [50, 40, 30], startup: 14, recovery: 18, ex: { dmg: 120, hits: 2, delay: [26, 26, 26] } },
      { id: 'takeover', name: 'HOSTILE TAKEOVER', input: 'dp', btn: 'p', modern: 'f', type: 'rising', dmg: [100, 120, 140], rise: [5.2, 6.4, 7.6], vx: 1.4, invuln: 6, startup: 3, recovery: 26, ex: { dmg: 170, hits: 3, invuln: 14 } },
    ],
    super: { name: 'MANDATORY TRAINING', type: 'demon', color: '#c040ff', line: 'MODULE 1 OF 47.' },
    quotes: ['THIS MEETING COULD HAVE BEEN AN EMAIL. YOUR CAREER, TOO.', 'I HAVE AN MD, AN MBA AND YOUR LUNCH.', 'MANDATORY TRAINING COMPLETE. YOU FAILED THE QUIZ.'],
    story: 'The Chief of Staff awaits atop St. World Warrior Medical Center. He has called a mandatory meeting. Attendance is death.',
    choice: ['RULE THE HOSPITAL', 'SEE ONE PATIENT'],
    endings: [
      'The Chief of Staff rules unopposed. His first act: a mandatory meeting about reducing meetings. It lasts 9 years.',
      'The Chief of Staff sees a patient for the first time in 30 years. "Say ahh," he says. He remembers why he became a doctor. Then his pager goes off.',
    ],
  },
];

export const FIGHTER_BY_ID = Object.fromEntries(FIGHTERS.map((f) => [f.id, f]));

export const DLC = [
  { name: 'TRAVEL NURSE', price: '1,999 CO-PAYS', note: 'ARRIVES IN 13 WEEKS' },
  { name: 'MED STUDENT', price: 'FREE (UNPAID)', note: 'WILL SHADOW YOU' },
  { name: 'HOSPITALIST', price: '2,499 CO-PAYS', note: 'ADMITS EVERYTHING' },
  { name: 'BILLING CODER', price: 'ICD-10: Z99.9', note: 'PENDING REVIEW' },
  { name: 'NIGHT SECURITY', price: '1,499 CO-PAYS', note: 'ON BREAK' },
  { name: 'THE LAWYER', price: '$$$$$', note: 'SUES ON CONTACT' },
];

// Who you fight at the end of Arcade / Grand Rounds.
export const BOSSES = ['admin', 'chief'];
